# Generated by Django 6.0.7 on 2026-07-29 09:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_core', '0004_airequestlog'),
        ('identity', '0004_brandprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_wallet', to='identity.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('grant', 'Grant (free plan allowance, promo, etc.)'), ('purchase', 'Purchase'), ('debit', 'Debit (AI usage)'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.IntegerField(help_text='Positive for grants/purchases/refunds, negative for debits.')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_ai_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai_core.airequestlog')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.creditwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
