# Generated by Django 6.0.7 on 2026-07-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderStatus',
            fields=[
                ('name', models.SlugField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('is_manually_disabled', models.BooleanField(default=False, help_text="Force this provider to show as 'coming soon' regardless of API key status.")),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
