# Generated by Django 6.0.7 on 2026-07-29 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0003_seed_remaining_providers'),
        ('identity', '0004_brandprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('prompt', models.TextField()),
                ('response_text', models.TextField(blank=True)),
                ('was_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to='identity.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
