# Generated by Django 6.0.7 on 2026-07-26 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_workspacemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('target_audience', models.TextField(blank=True)),
                ('preferred_tone', models.CharField(blank=True, max_length=100)),
                ('writing_style', models.TextField(blank=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('brand_keywords', models.JSONField(blank=True, default=list)),
                ('brand_colors', models.JSONField(blank=True, default=list)),
                ('social_accounts', models.JSONField(blank=True, default=dict)),
                ('goals', models.TextField(blank=True)),
                ('preferred_ai_provider', models.CharField(default='gemini', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_profile', to='identity.workspace')),
            ],
        ),
    ]
